version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: nodeapi
    working_dir: /usr/src/server
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/server/dist/
      - ./package.json:/usr/src/server/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo